project_id = "jvonopsvdnlmcemiauyh"

[functions.generate-thread]
verify_jwt = true

[functions.track-referral]
verify_jwt = false

[functions.admin-manage-subscription]
verify_jwt = true

[functions.send-refund-notification]
verify_jwt = false